[package]
name = "cargo-flutter"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
cargo = "0.41.0"
clap = "2.33.0"
env_logger = "0.7.1"
failure = "0.1.6"
log = "0.4.8"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5.5"
